name: social_media
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.0.3
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  fonts:
    - family: MartelSans
      fonts:
        - asset: assets/fonts/martelsans-regular.otf
  uses-material-design: true

  assets:
    - assets/images/

  generate: true
